- 
  name: 'airtable_geocode_sync.rb'
  schedule: "*/30 * * * *"
- 
  name: 'airtable_wishlist_sync.rb'
  schedule: "*/10 * * * *"
- 
  name: 'pocket_sync.rb'
  schedule: "*/10 * * * *"
-
  name: 'nexus_check.rb'
  schedule: "0 16 * * *"
-
  name: 'reminder.rb'
  schedule: "0 21 */2 * *"
  arguments:
    - "Cat Litter"
    - "Clean the cat litter"
-
  name: 'reminder.rb'
  schedule: "0 14 */2 * *"
  arguments:
    - "Cat Food"
    - "Fill the Cat Food"
