- 
  name: 'airtable_geocode_sync.rb'
  schedule: "*/30 * * * *"
- 
  name: 'airtable_wishlist_sync.rb'
  schedule: "*/10 * * * *"
- 
  name: 'medium_feed_sync.rb'
  schedule: "*/30 * * * *"
- 
  name: 'pocket_sync.rb'
  schedule: "*/10 * * * *"
-
  name: 'nexus_check.rb'
  schedule: "0 16 * * *"
-
  name: 'reminder.rb'
  schedule: "0 19 */2 * *"
  arguments:
    - "Cat Litter"
    - "Clean the cat litter"
